show databases;
use aditi;
create table proson1(ID INT, pro_name varchar(20),salary int,course varchar(20);
insert into proson1 value(101,"Akansh",1000,"MCA"),(101,"Anjali",2000,"MBA"),(101,"Riya",1000,"MCA"),(102,"Akansh",2000,"MBA"),(102,"Riya",2000,"MBA"),(103,"Anjali",1000,"MCA"),(103,"Akansh",2000,"MCA"),(104,"Anjali",1000,"MBA");
select*from proson1;
create table Fanshi1(ID INT, Fan_name varchar(20),salary int,course varchar(20));
insert into Fanshi1 value(101,"Akansh",1000,"MCA"),(101,"Anjali",2000,"MBA"),(102,"Riya",1000,"MCA"),(102,"Akansh",2000,"MBA"),(103,"Riya",2000,"MBA"),(104,"Akansh",1000,"MCA"),(105,"Riya",3000,"MBA")
;
select*from Fanshi1;
select P.ID,F.ID from Proson P inner join Fanshi F on P.course=F.course; 
select p.pro_name ,F.fan_name from proson P right join Fanshi F on P.ID=F.ID;
select*from Fanshi1;
select distinct Course from Fanshi1;
select Fan_name,Salary from Fanshi1;
select distinct course,Fan_name from Fanshi1;
select*from Fanshi1 where salary<=1000;
select*from Fanshi1 where course="MCA" AND Fan_name="Riya";
select*from Fanshi1 where salary<=15000 and Course="MBA";
select*from Fanshi1 where Course="MCA" or Fan_name="Akansh";
select*from Fanshi1 where ID>=101 or Course<="MBA";
select*from Fanshi1 where Course IN(10000);
select*from diwali_sales_analytics where Age in(28,16);
select*from diwali_sales_analytics where User_ID Not IN(1002903,1000588);
select*from diwali_sales_analytics where Orders between 1 and 2;
select*from diwali_sales_analytics where Amount  between 20908 and 20933;
select Cust_name, Gender, Age, State from diwali_sales_analytics;
select * from diwali_sales_analytics where Cust_name like 'A%';
select*from diwali_sales_analytics where Cust_name like 'M%';
select*from diwali_sales_analytics where Cust_name like 'R%';
select*from diwali_sales_analytics where State like '%a';
select*from diwali_sales_analytics where Cust_name like '%A';
select*from diwali_sales_analytics where Zone like '%n';
select*from diwali_sales_analytics where Zone like 'C%';
select*from diwali_sales_analytics where Zone like 'n%';
select*from diwali_sales_analytics where Zone like '%n';
select*from diwali_sales_analytics where Cust_name like '%n%';
select*from diwali_sales_analytics where State like '%m';
select*from diwali_sales_analytics where Cust_name like 'A__';
select*from diwali_sales_analytics where Cust_name like 'R__';
select*from diwali_sales_analytics where State like 'D__';
select*from diwali_sales_analytics where Product_Category like 'F%';
select*from diwali_sales_analytics where Cust_name like 'M__';
select*from diwali_sales_analytics where Cust_name Not like 'A%';
select*from diwali_sales_analytics limit 4;
select*from diwali_sales_analytics limit 10;
select*from diwali_sales_analytics limit 1,4;
select*from diwali_sales_analytics order by Age limit 1,4;
select*from diwali_sales_analytics order by Cust_name limit 6;
select*from diwali_sales_analytics order by Cust_name  desc limit 4;
select*from diwali_sales_analytics order by Occupation asc limit 7;
select*from diwali_sales_analytics order by Zone desc limit 5 ;
select*from diwali_sales_analytics where User_ID not in(1,3);
select*from diwali_sales_analytics where state not in(1,5);
select*from diwali_sales_analytics where Amount between 21503 and 21563;
select*from diwali_sales_analytics where Cust_name not like 'A%';
select*from diwali_sales_analytics limit 5;
select*from diwali_sales_analytics limit 0,4;
select*from diwali_sales_analytics limit 1,9;
select*from diwali_sales_analytics order by Amount desc;
select*from diwali_sales_analytics  order by Amount Asc;
select*from diwali_sales_analytics order by Amount Desc limit 1,3;
select*from diwali_sales_analytics order by PRODUCT_ID ASC LIMIT 1,1;
select*from diwali_sales_analytics where Cust_name is null;
select*from diwali_sales_analytics where Marital_Status is not null;
select*from diwali_sales_analytics order by Cust_name;
select*from diwali_sales_analytics order by Cust_name Desc;
select*from diwali_sales_analytics order by Amount desc;
select*from diwali_sales_analytics order by Amount Desc, Cust_name Asc;
select*from diwali_sales_analytics order by State Desc, Age Asc;
select*from emaloyee3;
select*from diwali_sales_analytics;
show databases;
use nikhil;
create table Function_data (User_ID int,Cust_name varchar(10),Age int,State varchar(8));
insert into Function_data value(100931,"Shikha",22,"MP"),(100932,"Anjali",45,"Delhi"),(100934,"Riya",18,"Gao"),(100946,"Aadi",47,"Satna"),(100947,"Shreya",25,"jabalpur");
select*from Function_data;
select D.Cust_name,F.Cust_name from diwali_sales_analytics D Inner join Function_name F on D.User_ID=F.User_ID;
